// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Apr 18 14:39:30 2024

vga_adapter vga_adapter_inst
(
	.Reset_L(Reset_L_sig) ,	// input  Reset_L_sig
	.Clk(Clk_sig) ,	// input  Clk_sig
	.Address(Address_sig) ,	// input [11:0] Address_sig
	.Data_in(Data_in_sig) ,	// input [7:0] Data_in_sig
	.GraphicsCS_L(GraphicsCS_L_sig) ,	// input  GraphicsCS_L_sig
	.WE_L(WE_L_sig) ,	// input  WE_L_sig
	.AS_L(AS_L_sig) ,	// input  AS_L_sig
	.R(R_sig) ,	// output [7:0] R_sig
	.G(G_sig) ,	// output [7:0] G_sig
	.B(B_sig) ,	// output [7:0] B_sig
	.VGA_HS(VGA_HS_sig) ,	// output  VGA_HS_sig
	.VGA_VS(VGA_VS_sig) ,	// output  VGA_VS_sig
	.VGA_BLANK_N(VGA_BLANK_N_sig) ,	// output  VGA_BLANK_N_sig
	.VGA_SYNC_N(VGA_SYNC_N_sig) ,	// output  VGA_SYNC_N_sig
	.DataOut(DataOut_sig) ,	// output [7:0] DataOut_sig
	.VGA_CLK(VGA_CLK_sig) 	// output  VGA_CLK_sig
);

